#############################################
# SMTP server queue configuration
#############################################

[queue]
path = "%{BASE_PATH}%/queue"
hash = 64

[queue.schedule]
retry = ["2m", "5m", "10m", "15m", "30m", "1h", "2h"]
notify = ["1d", "3d"]
expire = "5d"

[queue.outbound]
next-hop = [ { if = "rcpt-domain", in-list = "%{DEFAULT_DIRECTORY}%/domains", then = "local" },
{% if mail['relay']['enabled'] %}
             { else = "relay" } ]
{% else %}
             { else = false } ]
{% endif %}
ip-strategy = "ipv4-then-ipv6"

[queue.outbound.tls]
{% if mail['relay']['enabled'] %}
dane = "disable"
mta-sts = "disable"
{% else %}
ane = "optional"
mta-sts = "optional"
{% endif %}
starttls = "require"
allow-invalid-certs = false

#[queue.outbound.source-ip]
#v4 = ["10.0.0.10", "10.0.0.11"]
#v6 = ["a::b", "a::c"]

[queue.outbound.limits]
mx = 7
multihomed = 2

[queue.outbound.timeouts]
connect = "3m"
greeting = "3m"
tls = "2m"
ehlo = "3m"
mail-from = "3m"
rcpt-to = "3m"
data = "10m"
mta-sts = "2m"

[[queue.quota]]
#match = {if = "sender-domain", eq = "foobar.org"}
#key = ["rcpt"]
messages = 100000
size = 10737418240 # 10gb

[[queue.throttle]]
key = ["rcpt-domain"]
#rate = "100/1h"
concurrency = 5
