#############################################
# SMTP remote servers configuration
#############################################

[remote."local"]
address = "127.0.0.1"
port = 11200
protocol = "lmtp"
concurrency = 10
timeout = "1m"

[remote."local".tls]
implicit = false
allow-invalid-certs = true

{% if mail['relay']['enabled'] %}
[remote."relay"]
address = "mail['relay']['domain']"
port = "mail['relay']['port']"
protocol = "smtp"
concurrency = 10
timeout = "1m"

[remote."relay".auth]
username = "{{ mail['relay']['auth']['username'] }}"
secret = "{{ mail['relay']['auth']['secret'] }}"

[remote."relay".tls]
implicit = false
allow-invalid-certs = false
{% endif %}

#[remote."local".auth]
#username = ""
#secret = ""
