#############################################
# JMAP authentication & session configuration
#############################################

[jmap]
directory = "%{DEFAULT_DIRECTORY}%"

[jmap.session.cache]
ttl = "1h"
size = 100

[jmap.session.purge]
frequency = "15 * *"
