#############################################
# IMAP Directory configuration
#############################################

[directory."imap"]
type = "imap"
address = "127.0.0.1"
port = 993
disable = true

[directory."imap".pool]
max-connections = 10

[directory."imap".pool.timeout]
create = "30s"
wait = "30s"
recycle = "30s"

[directory."imap".tls]
implicit = true
allow-invalid-certs = true

[directory."imap".cache]
entries = 500
ttl = {positive = '1h', negative = '10m'}

[directory."imap".lookup]
domains = ["%{DEFAULT_DOMAIN}%"]

