---
- name: Ensure directory structure exists
  ansible.builtin.file:
    path: './stacks/web/{{ item.path }}'
    state: directory
  with_community.general.filetree: ../templates/
  when: item.state == 'directory'

- name: Ensure files are populated from templates
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: './stacks/web/{{ item.path }}'
  with_community.general.filetree: ../templates/
  when: item.state == 'file'

- name: Create private key file for dkim
  copy:
    dest: "./stacks/web/mail/etc/dkim/{{ base_domain }}.key"
    content: |
      {{ mail['dkim_private_key'] }}

- name: Copy spamfilter
  copy:
    src: mail/etc/spamfilter
    dest: ./stacks/web/mail/etc/

- name: Create stalwart's required dirs if it does not exist
  ansible.builtin.file:
    path: ./stacks/web/mail/{{ item }}
    state: directory
    mode: '0755'
  loop:
    - bin
    - data
    - logs
    - queue
    - reports

- name: Copy compose.yml
  copy:
    src: compose.yml
    dest: ./stacks/web/

- name: Copy static web
  copy:
    src: web/
    dest: ./stacks/web/web/

- name: Deploy web stack from a compose file
  community.docker.docker_stack:
    state: present
    prune: true
    name: web
    compose:
      - ./stacks/web/compose.yml
