#############################################
# JMAP server listener configuration
#############################################

[server.listener."jmap"]
bind = ["[::]:8080"]
url = "https://%{HOST}%:8080"
protocol = "jmap"
