version: "3"

services:
  mail:
    image: stalwartlabs/mail-server:latest
    ports:
      - 8080:8080
      - 25:25
      - 587:587
      - 465:465
      - 143:143
      - 993:993
      - 4190:4190
    volumes:
      - ./data:/opt/stalwart-mail
